# Pytorch Library

In [44]:
import torch
import math
import numpy as np

In [2]:
print("Pytorch Library")

Pytorch Library


***Matrix of Zeros***

 We create a matrix of 5 rows and 2 columns. Torch.zeros function will print zeros in the matrix.

In [3]:
a= torch.zeros(5,2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
a.dtype

torch.float32

## Tensors

***Pytorch Tensors***

In Pytorch, tensor is a multi-dimensional array that can be used to represent and manipulate numerical data.r.
sor.Tensors are a fundamental data structure in PyTorch and serve as the building blocks for creating and working with various machine learning models and algorithms. Tensors are similar to NumPy arrays but with additional capabilities optimized for deep learning and GPU acceleration(speeds up numerical computations, especially for deep learning tasks).

In [5]:
b = torch.ones((5,3) , dtype= torch.int32)
b

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

***Random Tensor***

 A random tensor is a multi-dimensional array filled with random values. Random tensors are used for various purposes, such as initializing weights in neural networks, data augmentation, and creating random noise for simulations.

In [6]:
r1= torch.rand(2,2)
r1

tensor([[0.0738, 0.7554],
        [0.8400, 0.9526]])

***Random Seed***

A random seed is used to initialize random generator which is used to generate random values. If we give same seed to 2 different variables both will get same values.

In [7]:
torch.manual_seed(1792)
r1= torch.rand(2,2)
print("First Random Values")
r1

First Random Values


tensor([[0.7809, 0.6418],
        [0.5344, 0.6687]])

In [8]:
torch.manual_seed(1792)
r= torch.rand(2,2)
print("Second Random Values")
r

Second Random Values


tensor([[0.7809, 0.6418],
        [0.5344, 0.6687]])

***Dimensional Tensors***
- 1-dimensional tensor called a vector.
  
- 2-dimensional tensor is often referred to as a matrix.

- Anything with more than two dimensions is generally just called a tensor.

***1 Dimensional***

In [9]:
d = torch.tensor([1, 2, 3, 4, 5])
d

tensor([1, 2, 3, 4, 5])

***2 Dimensional***
- shape function tell us the size of the dimensional tensors.
- ndim function tell us that the particular tensor belongs to which dimension.

In [10]:
d1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
d1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
d1.shape

torch.Size([2, 3])

***Creating tensors using arange function***


In [12]:
range= torch.arange(0, 10, step=2)
range

tensor([0, 2, 4, 6, 8])

In [13]:
print(range.shape)
range.ndim

torch.Size([5])


1

***Creation of 3D tensor***

In [14]:
x = torch.ones(2, 2, 3)
print(x.shape)
print(x)
print("Dimensions is:")
print(x.ndim)

torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
Dimensions is:
3


In [15]:
print(x*2)

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])


***Various Mathematical Operations***

In [16]:
p = (torch.ones(2, 2) * 7 - 1) / 2
t= (torch.ones(2,2)*2)
f = t ** 2
s = t ** 0.5
print(t)
print(f)
print(s)
print(p)

tensor([[2., 2.],
        [2., 2.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
tensor([[3., 3.],
        [3., 3.]])


- 0: This represents an angle of 0 radians.
math.pi / 4
-  This represents an angle of π/4 radians, which is 45 degrees
math.pi / 
- 2: This represents an angle of π/2 radians, which is 90 degree .
3 * math.pi /
-  4: This represents an angle of 3π/4 radians, which is 135 degre
-  sines calculate sin of the angl
-  asine calculates inverse of sin.es.

In [17]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print(angles)

tensor([0.0000, 0.7854, 1.5708, 2.3562])


In [18]:
sines = torch.sin(angles)
inverses = torch.asin(sines)
print(sines)
print(inverses)

tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


***Bitwise_xor***

Bitwise_xor operation returns 1 for different operands and 0 for same operands. It compares the value placed at same indexes in both tensors and perform bitwise operations.

In [25]:
d1

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.bitwise_xor(d1,d1)

In [23]:
d2 = torch.tensor([[1, 2, 7], [4, 4, 6]])
d2

tensor([[1, 2, 7],
        [4, 4, 6]])

In [24]:
torch.bitwise_xor(d1,d2)

tensor([[0, 0, 4],
        [0, 1, 0]])

In [29]:
print(d1.max())
d1.min()

tensor(6)


tensor(1)

***Copying a Tensor***

In [32]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(a)
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[  1., 561.],
        [  1.,   1.]])


***Checking Availability of GPU***

In [33]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


***unsqueeze***
  is used to add additional dimension to the tensor. unsqueeze is of 1 dimension and it adds one dimension to the given matrix.

***squeeze*** 
   is used to remove the dimension of the tensor.

In [36]:
a = torch.rand(3, 226, 226)
a= a.unsqueeze(1)
print(a.shape)

torch.Size([3, 1, 226, 226])


In [40]:
a = torch.rand(3, 226, 226)
a= a.squeeze(1)
print(a.shape)

torch.Size([3, 226, 226])


### Comparison Between Numpy and Tensors

***1. Creation***

In [46]:
n = np.array([1, 2, 3])
print("NumPy Array:", n)
t = torch.tensor([1, 2, 3])
print("PyTorch Tensor:", t)

NumPy Array: [1 2 3]
PyTorch Tensor: tensor([1, 2, 3])


***2. Reshaping***

In [53]:
n= np.array([1, 2, 3, 4, 5, 6])
r = n.reshape(2, 3)
print("NumPy Reshaped Array:\n", r)
t = torch.tensor([1, 2, 3, 4, 5, 6])
e = t.view(2, 3)
print("PyTorch Reshaped Tensor:\n", e)

NumPy Reshaped Array:
 [[1 2 3]
 [4 5 6]]
PyTorch Reshaped Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


***3. GPU Availability***

In Numpy there is no built-in GRU support while PyTorch has additional features optimized for deep learning, such as GPU support and automatic differentiation for neural network training.If PyTorch is running on a GPU and NumPy is not, there can be significant differences in terms of performance and capabilities.

## Normalization